# define HttpFieldItem		object "/usr/HTTP/api/lib/FieldItem"
# define HttpAuthentication	object "/usr/HTTP/api/lib/Authentication"
# define RemoteHttpAuthentication object "/usr/HTTP/api/lib/RemoteAuthentication"
# define HttpProduct		object "/usr/HTTP/api/lib/Product"
# define HttpTime		object "/usr/HTTP/api/lib/Time"
# define RemoteHttpTime		object "/usr/HTTP/api/lib/RemoteTime"

# define HttpField		object "/usr/HTTP/api/lib/Field"
# define HttpFields		object "/usr/HTTP/api/lib/Fields"
# define RemoteHttpFields	object "/usr/HTTP/api/lib/RemoteFields"
