# define Asn1			object "/usr/TLS/api/lib/Asn1"
# define Asn1Der		object "/usr/TLS/api/lib/Asn1Der"

# define CLASS_UNIVERSAL	0
# define CLASS_APPLICATION	1
# define CLASS_CONTEXTUAL	2
# define CLASS_PRIVATE		3

# define ASN1_BOOLEAN		 1
# define ASN1_INTEGER		 2
# define ASN1_BIT_STRING	 3
# define ASN1_OCTET_STRING	 4
# define ASN1_NULL		 5
# define ASN1_OBJECT_IDENTIFIER	 6
# define ASN1_OBJECT_DESCRIPTOR	 7
# define ASN1_EXTERNAL		 8
# define ASN1_REAL		 9
# define ASN1_ENUMERATED	10
# define ASN1_EMBEDDED_PDV	11
# define ASN1_UTF8_STRING	12
# define ASN1_RELATIVE_OID	13
# define ASN1_TIME		14
# define ASN1_SEQUENCE		16
# define ASN1_SEQUENCE_OF	16
# define ASN1_SET		17
# define ASN1_SET_OF		17
# define ASN1_NUMERIC_STRING	18
# define ASN1_PRINTABLE_STRING	19
# define ASN1_T61_STRING	20
# define ASN1_VIDEOTEX_STRING	21
# define ASN1_IA5_STRING	22
# define ASN1_UTC_TIME		23
# define ASN1_GENERALIZED_TIME	24
# define ASN1_GRAPHIC_STRING	25
# define ASN1_VISIBLE_STRING	26
# define ASN1_GENERAL_STRING	27
# define ASN1_UNIVERSAL_STRING	28
# define ASN1_CHARACTER_STRING	29
# define ASN1_BMP_STRING	30
# define ASN1_DATE		31
# define ASN1_TIME_OF_DAY	32
# define ASN1_DATE_TIME		33
# define ASN1_DURATION		34
