# define Extension	object "/usr/TLS/lib/record/Extension"


# define EXT_SERVER_NAME				0
# define EXT_MAX_FRAGMENT_LENGTH			1
# define EXT_STATUS_REQUEST				5
# define EXT_SUPPORTED_GROUPS				10
# define EXT_SIGNATURE_ALGORITHMS			13
# define EXT_USE_SRTP					14
# define EXT_HEARTBEAT					15
# define EXT_APPLICATION_LAYER_PROTOCOL_NEGOTIATION	16
# define EXT_SIGNED_CERTIFICATE_TIMESTAMP		18
# define EXT_CLIENT_CERTIFICATE_TYPE			19
# define EXT_SERVER_CERTIFICATE_TYPE			20
# define EXT_PADDING					21
# define EXT_PRE_SHARED_KEY				41
# define EXT_EARLY_DATA					42
# define EXT_SUPPORTED_VERSIONS				43
# define EXT_COOKIE					44
# define EXT_PSK_KEY_EXCHANGE_MODES			45
# define EXT_CERTIFICATE_AUTHORITIES			47
# define EXT_OID_FILTERS				48
# define EXT_POST_HANDSHAKE_AUTH			49
# define EXT_SIGNATURE_ALGORITHMS_CERT			50
# define EXT_KEY_SHARE					51
